
(function(){
'use strict';
const ASSET_KEY='bongdam_rpg_editor_assets_v3';
const $=id=>document.getElementById(id);
const MIN_SIZE=0.006, HANDLE_SIZE=16, HANDLE_HIT=24;
const BUILTIN_KEYS=['','small','shop','store24','cafe','tall','hall','corner','books','library','youth','park','fountain','playground','portal'];
const v32={assets:[],cache:new Map(),resizing:false,handle:'',start:null,place:false,renderPatched:false,bound:false};
function ed(){return window.BongdamEditor||null}function stt(){return ed()?ed().state:null}function cv(){return $('game-canvas')}function clamp(v,a,b){v=Number(v);return Number.isFinite(v)?Math.max(a,Math.min(b,v)):a}function clamp01(v){return clamp(v,0,1)}function stage(){return typeof STAGES!=='undefined'&&typeof currentStage!=='undefined'?STAGES[currentStage]:null}function objs(){const s=stage();return s&&Array.isArray(s.objects)?s.objects:[]}function obj(){const s=stt(),l=objs();return s&&s.selectedIndex>=0&&s.selectedIndex<l.length?l[s.selectedIndex]:null}function hasCol(o){return o&&o.cx!==undefined&&o.cy!==undefined&&o.cw!==undefined&&o.ch!==undefined}function rect(o){return{x:Number(o.rx||0),y:Number(o.ry||0),w:Number(o.rw||.08),h:Number(o.rh||.08)}}function setRect(o,r){o.rx=clamp01(r.x);o.ry=clamp01(r.y);o.rw=clamp(r.w,MIN_SIZE,1);o.rh=clamp(r.h,MIN_SIZE,1)}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(m){const t=$('bge-toast');if(t){t.textContent=m;t.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>t.style.display='none',1800)}else console.log(m)}
function loadAssets(){try{v32.assets=JSON.parse(localStorage.getItem(ASSET_KEY)||'[]');if(!Array.isArray(v32.assets))v32.assets=[]}catch(e){v32.assets=[]}}
function saveAssets(){try{localStorage.setItem(ASSET_KEY,JSON.stringify(v32.assets))}catch(e){alert('에셋 저장 실패: 이미지 용량이 너무 큽니다. 512~1024px 이하 PNG/JPG를 권장합니다.')}}
function asset(id){return v32.assets.find(a=>a.id===id)||null}function assetId(o){if(!o)return'';if(o.assetId)return o.assetId;if(typeof o.key==='string'&&o.key.startsWith('asset:'))return o.key.slice(6);return''}function setAsset(o,id){if(!o)return;if(id){o.assetId=id;o.key='asset:'+id;o.customImage=true}else{delete o.assetId;delete o.customImage;if(String(o.key||'').startsWith('asset:'))o.key=''}}
function img(id){const a=asset(id);if(!a||!a.dataUrl)return null;if(v32.cache.has(id))return v32.cache.get(id);const im=new Image();im.onload=()=>{if(ed())ed().refresh()};im.src=a.dataUrl;v32.cache.set(id,im);return im}
function viewportW(){const fixed=window.BD_getEditorViewportV26&&window.BD_getEditorViewportV26();const s=stt();return fixed?fixed.w:(s&&s.enabled?1/s.editorZoom:(typeof VIEWPORT_W!=='undefined'?VIEWPORT_W:1))}function viewportH(){const fixed=window.BD_getEditorViewportV26&&window.BD_getEditorViewportV26();const s=stt();return fixed?fixed.h:(s&&s.enabled?1/s.editorZoom:(typeof VIEWPORT_H!=='undefined'?VIEWPORT_H:1))}
function mapToCanvas(mx,my){const c=cv(),vw=viewportW(),vh=viewportH();const bx=((mx-camX)/vw+.5)*BASE_W,by=((my-camY)/vh+.5)*BASE_H;return{x:(bx-BASE_W/2)*currentScale+c.width/2,y:(by-BASE_H/2)*currentScale+c.height/2}}
function canvasToMap(cx,cy){const c=cv(),r=c.getBoundingClientRect();const sx=(cx-r.left)*(c.width/r.width),sy=(cy-r.top)*(c.height/r.height);const bx=(sx-c.width/2)/currentScale+BASE_W/2,by=(sy-c.height/2)/currentScale+BASE_H/2;return{x:clamp01((bx/BASE_W-.5)*viewportW()+camX),y:clamp01((by/BASE_H-.5)*viewportH()+camY),sx,sy}}
function drawAssets(ctx){objs().forEach(o=>{const id=assetId(o);if(!id||o.hidden)return;const im=img(id);if(!im||!im.complete||im.naturalWidth<=0)return;const r=rect(o),p1=mapToCanvas(r.x,r.y),p2=mapToCanvas(r.x+r.w,r.y+r.h);ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(im,p1.x,p1.y,p2.x-p1.x,p2.y-p1.y);ctx.restore()})}
function handles(r){const x1=r.x,y1=r.y,x2=r.x+r.w,y2=r.y+r.h,cx=r.x+r.w/2,cy=r.y+r.h/2;return[['nw',x1,y1],['n',cx,y1],['ne',x2,y1],['e',x2,cy],['se',x2,y2],['s',cx,y2],['sw',x1,y2],['w',x1,cy]]}
function drawHandles(ctx){const s=stt(),o=obj();if(!s||!s.enabled||!o||s.selectedPart==='collider')return;const r=rect(o),p1=mapToCanvas(r.x,r.y),p2=mapToCanvas(r.x+r.w,r.y+r.h);ctx.save();ctx.strokeStyle='#00e1ff';ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.strokeRect(p1.x,p1.y,p2.x-p1.x,p2.y-p1.y);ctx.setLineDash([]);handles(r).forEach(h=>{const p=mapToCanvas(h[1],h[2]);ctx.fillStyle='#fff3a3';ctx.strokeStyle='#052339';ctx.lineWidth=2;ctx.fillRect(p.x-HANDLE_SIZE/2,p.y-HANDLE_SIZE/2,HANDLE_SIZE,HANDLE_SIZE);ctx.strokeRect(p.x-HANDLE_SIZE/2,p.y-HANDLE_SIZE/2,HANDLE_SIZE,HANDLE_SIZE)});ctx.restore()}
function patchRender(){if(v32.renderPatched||typeof renderMap!=='function')return;const prev=renderMap;renderMap=function(c){prev(c);/* (v261) 이중 렌더 제거 */};v32.renderPatched=true}
function cursor(h){if(h==='n'||h==='s')return'ns-resize';if(h==='e'||h==='w')return'ew-resize';if(h==='nw'||h==='se')return'nwse-resize';return'nesw-resize'}
function hit(cx,cy){return'';const s=stt(),o=obj();if(!s||!s.enabled||!o||s.selectedPart==='collider')return'';const p=canvasToMap(cx,cy),r=rect(o);/* (v240k-3) 화면px 기준 판정 + 본체 내부는 이동 우선 */const _c=cv(),_rc=_c.getBoundingClientRect();const _k=(_rc.width&&_c.width)?(_rc.width/_c.width):1;const _a=mapToCanvas(r.x,r.y),_b=mapToCanvas(r.x+r.w,r.y+r.h);if(p.sx>_a.x+2&&p.sx<_b.x-2&&p.sy>_a.y+2&&p.sy<_b.y-2)return'';for(const h of handles(r)){const hp=mapToCanvas(h[1],h[2]);const dx=p.sx-hp.x,dy=p.sy-hp.y;if(Math.hypot(dx,dy)*_k<=HANDLE_HIT)return h[0]}return''}
function startResize(h,e){const o=obj(),s=stt();if(!o||!s)return;v32.resizing=true;v32.handle=h;v32.start={mouse:canvasToMap(e.clientX,e.clientY),rect:rect(o),col:hasCol(o)?{cx:+o.cx,cy:+o.cy,cw:+o.cw,ch:+o.ch}:null};s.dragging=false;s.dragMode=null;cv().style.cursor=cursor(h)}
function updateResize(e){if(!v32.resizing||!v32.start)return;const o=obj();if(!o)return;const p=canvasToMap(e.clientX,e.clientY),st=v32.start,r=st.rect,dx=p.x-st.mouse.x,dy=p.y-st.mouse.y;let x=r.x,y=r.y,w=r.w,h=r.h,hd=v32.handle;if(hd.includes('e'))w=r.w+dx;if(hd.includes('s'))h=r.h+dy;if(hd.includes('w')){x=r.x+dx;w=r.w-dx}if(hd.includes('n')){y=r.y+dy;h=r.h-dy}if(w<MIN_SIZE){if(hd.includes('w'))x=r.x+r.w-MIN_SIZE;w=MIN_SIZE}if(h<MIN_SIZE){if(hd.includes('n'))y=r.y+r.h-MIN_SIZE;h=MIN_SIZE}x=clamp(x,0,1-MIN_SIZE);y=clamp(y,0,1-MIN_SIZE);w=Math.min(w,1-x);h=Math.min(h,1-y);setRect(o,{x,y,w,h});if(hasCol(o)&&st.col){const rx=(st.col.cx-r.x)/Math.max(r.w,MIN_SIZE),ry=(st.col.cy-r.y)/Math.max(r.h,MIN_SIZE),rw=st.col.cw/Math.max(r.w,MIN_SIZE),rh=st.col.ch/Math.max(r.h,MIN_SIZE);o.cx=clamp01(o.rx+o.rw*rx);o.cy=clamp01(o.ry+o.rh*ry);o.cw=clamp(o.rw*rw,MIN_SIZE,1);o.ch=clamp(o.rh*rh,MIN_SIZE,1)}syncNumbers(o);if(ed())ed().refresh()}
function endResize(){if(!v32.resizing)return;v32.resizing=false;v32.handle='';v32.start=null;if(cv())cv().style.cursor='';if(ed()){ed().save(false);ed().refresh()}toast('크기 변경 저장됨')}
function syncNumbers(o){['rx','ry','rw','rh','cx','cy','cw','ch'].forEach(k=>{const el=$('bge-obj-'+k);if(el&&o[k]!==undefined)el.value=Number(o[k]).toFixed(3)})}
function makePanel(){if($('bge-v32-asset-panel'))return;const host=$('bge-panel')||document.body;const box=document.createElement('div');box.id='bge-v32-asset-panel';box.innerHTML=`
<h4>이미지 / 스프라이트 적용 v3.2</h4>
<div id="bge-v32-current">오브젝트를 선택하면 현재 이미지 상태가 표시됩니다.</div>
<div class="row"><div><label>기본 이미지 Key</label><select id="bge-v32-key"></select></div><div><label>업로드 이미지 에셋</label><select id="bge-v32-asset"></select></div></div>
<div class="btnrow"><button id="bge-v32-apply-key" type="button">기본 Key 적용</button><button id="bge-v32-apply-asset" type="button">업로드 이미지 적용</button><button id="bge-v32-clear" class="warn" type="button">이미지 해제</button></div>
<label>외부 PC/폴더에서 이미지 여러 개 가져오기</label><input id="bge-v32-import-images" type="file" accept="image/*" multiple>
<div class="row"><div><label>씬에 배치할 에셋</label><select id="bge-v32-place-asset"></select></div><div><label>에셋 배치</label><button id="bge-v32-place-mode" class="warn" type="button" style="width:100%;margin-top:0">씬에 배치 시작</button></div></div>
<div class="btnrow"><button id="bge-v32-export-pack" type="button">에셋팩 내보내기</button><button id="bge-v32-import-pack-btn" type="button">에셋팩 가져오기</button></div><input id="bge-v32-import-pack" type="file" accept="application/json,.json" style="display:none">
<div id="bge-v32-help">사용법: 오브젝트 선택 → 업로드 이미지 에셋 선택 → 업로드 이미지 적용. 기본 Key는 기존 내장 건물 이미지용입니다.</div>`;
const h=host.querySelector('h3'); if(h&&h.nextSibling)host.insertBefore(box,h.nextSibling); else host.appendChild(box);
BUILTIN_KEYS.forEach(k=>{const op=document.createElement('option');op.value=k;op.textContent=k?k:'없음';$('bge-v32-key').appendChild(op)});
$('bge-v32-key').addEventListener('change',applyKey);$('bge-v32-apply-key').addEventListener('click',applyKey);$('bge-v32-asset').addEventListener('change',applyAsset);$('bge-v32-apply-asset').addEventListener('click',applyAsset);$('bge-v32-clear').addEventListener('click',()=>{const o=obj();if(!o)return alert('오브젝트를 먼저 선택하세요.');setAsset(o,'');o.key='';const ki=$('bge-obj-key');if(ki)ki.value='';saveRefresh('이미지 해제 완료')});
$('bge-v32-import-images').addEventListener('change',function(){importImages(this.files);this.value=''});$('bge-v32-place-mode').addEventListener('click',()=>{v32.place=!v32.place;const s=stt();if(s)s.tool='select';updatePlaceBtn();toast(v32.place?'맵을 클릭하면 선택 에셋이 배치됩니다.':'에셋 배치 종료')});$('bge-v32-export-pack').addEventListener('click',exportPack);$('bge-v32-import-pack-btn').addEventListener('click',()=>$('bge-v32-import-pack').click());$('bge-v32-import-pack').addEventListener('change',function(){const f=this.files&&this.files[0];if(f)importPack(f);this.value=''})}
function refreshSelects(){['bge-v32-asset','bge-v32-place-asset'].forEach(id=>{const sel=$(id);if(!sel)return;const prev=sel.value;sel.innerHTML='<option value="">에셋 선택</option>';v32.assets.forEach(a=>{const op=document.createElement('option');op.value=a.id;op.textContent=a.name||a.id;sel.appendChild(op)});if(prev&&asset(prev))sel.value=prev});refreshPanel()}
function refreshPanel(){const o=obj(),cur=$('bge-v32-current');if(!cur)return;const keySel=$('bge-v32-key'),asSel=$('bge-v32-asset');if(!o){cur.textContent='오브젝트를 선택하면 현재 이미지 상태가 표시됩니다.';if(keySel)keySel.value='';if(asSel)asSel.value='';return}const id=assetId(o),a=asset(id);if(keySel)keySel.value=String(o.key||'').startsWith('asset:')?'':(o.key||'');if(asSel)asSel.value=id||'';if(a)cur.innerHTML='<img src="'+a.dataUrl+'"><div><b>'+esc(a.name||a.id)+'</b><br>업로드 이미지 적용 중</div>';else cur.innerHTML='<div><b>기본 Key:</b> '+esc(o.key||'없음')+'<br>업로드 이미지를 적용하면 씬에서 바로 보입니다.</div>'}
function applyKey(){const o=obj();if(!o)return alert('오브젝트를 먼저 선택하세요.');const k=$('bge-v32-key').value;setAsset(o,'');o.key=k;const ki=$('bge-obj-key');if(ki)ki.value=k;saveRefresh('기본 이미지 Key 적용 완료')}
function applyAsset(){const o=obj();if(!o)return alert('오브젝트를 먼저 선택하세요.');const id=$('bge-v32-asset').value;if(!id)return;setAsset(o,id);const ki=$('bge-obj-key');if(ki)ki.value='asset:'+id;saveRefresh('업로드 이미지 적용 완료')}
function saveRefresh(m){if(ed()){ed().save(false);ed().refresh()}refreshPanel();toast(m)}
function importImages(files){const list=Array.from(files||[]).filter(f=>f.type&&f.type.startsWith('image/'));if(!list.length)return alert('이미지 파일을 선택하세요.');let done=0;list.forEach(f=>{const r=new FileReader();r.onload=()=>{const id='asset_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6);v32.assets.push({id,name:f.name.replace(/\.[^.]+$/,''),dataUrl:String(r.result||'')});if(++done===list.length){saveAssets();refreshSelects();toast(list.length+'개 이미지 가져오기 완료')}};r.readAsDataURL(f)})}
function exportPack(){const blob=new Blob([JSON.stringify({version:'bongdam_asset_pack_v32',savedAt:new Date().toISOString(),assets:v32.assets},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bongdam_asset_library_pack_v32.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function importPack(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result||'{}')),arr=Array.isArray(d.assets)?d.assets:[];if(!arr.length)throw Error('assets 배열이 없습니다.');const ids=new Set(v32.assets.map(a=>a.id));arr.forEach(a=>{if(!a||!a.dataUrl)return;let id=a.id||'asset_'+Date.now().toString(36);if(ids.has(id))id+='_'+Math.random().toString(36).slice(2,5);ids.add(id);v32.assets.push({id,name:a.name||id,dataUrl:a.dataUrl})});saveAssets();refreshSelects();if(ed())ed().refresh();toast('에셋팩 가져오기 완료')}catch(e){alert('에셋팩 가져오기 실패: '+e.message)}};r.readAsText(file,'utf-8')}
function createAt(mx,my){const st=stage(),id=$('bge-v32-place-asset').value,a=asset(id);if(!st||!a)return alert('배치할 에셋을 선택하세요.');if(!Array.isArray(st.objects))st.objects=[];const o={_editorId:'v32_asset_'+Date.now().toString(36),type:'prop',label:a.name||'이미지 오브젝트',key:'asset:'+id,assetId:id,customImage:true,rx:clamp01(mx-.05),ry:clamp01(my-.05),rw:.1,rh:.1,cx:clamp01(mx-.05),cy:clamp01(my+.01),cw:.1,ch:.035,interactable:'',note:''};st.objects.push(o);const s=stt();if(s){s.selectedIndex=st.objects.length-1;s.selectedPart='object';s.tool='select'}v32.place=false;updatePlaceBtn();saveRefresh('에셋을 씬에 배치했습니다')}
function updatePlaceBtn(){const b=$('bge-v32-place-mode');if(b){b.textContent=v32.place?'씬 배치 중지':'씬에 배치 시작';b.classList.toggle('danger',v32.place)}}
function bindCanvas(){const c=cv();if(!c||v32.bound)return;v32.bound=true;c.addEventListener('mousedown',e=>{const s=stt();if(!s||!s.enabled)return;const h=hit(e.clientX,e.clientY);if(h&&e.button===0){e.preventDefault();e.stopImmediatePropagation();startResize(h,e);return}if(v32.place&&e.button===0){e.preventDefault();e.stopImmediatePropagation();const p=canvasToMap(e.clientX,e.clientY);createAt(p.x,p.y)}},true);c.addEventListener('mousemove',e=>{const s=stt();if(!s||!s.enabled)return;if(v32.resizing){e.preventDefault();e.stopImmediatePropagation();updateResize(e);return}const h=hit(e.clientX,e.clientY);if(h)c.style.cursor=cursor(h)},true);window.addEventListener('mouseup',endResize,true)}
function patchRefresh(){const E=ed();if(!E||E._v32RefreshPatched)return;const old=E.refresh;E.refresh=function(){old();refreshSelects()};E._v32RefreshPatched=true}
function poll(){const s=stt(),panel=$('bge-v32-asset-panel');if(panel&&s)panel.style.display=s.enabled?'block':'none';const o=obj();if(poll.last!==o){poll.last=o;refreshPanel()}requestAnimationFrame(poll)}
function init(){if(!ed()||typeof STAGES==='undefined'||!cv())return setTimeout(init,150);loadAssets();makePanel();refreshSelects();patchRender();patchRefresh();bindCanvas();poll();window.BongdamEditorV32={refresh:()=>{loadAssets();refreshSelects();if(ed())ed().refresh()},assets:v32.assets};toast('v3.2 이미지/스프라이트 패치 로드 완료')}
/* (v268) 구세대 모듈 부트 차단 — v3.2 (v5.2 에디터로 일원화) */
})();
